name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start container
        run: |
          docker-compose up -d

      - name: View logs
        run: |
          docker logs netsky
